Add timeout by dataset size
zilliztech/VectorDBBench pull request #171
Opened 2023-06-30 08:27 UTC by XuanYang-cn

2023-06-30 08:28 UTC, XuanYang-cn commented
![image](https://github.com/zilliztech/VectorDBBench/assets/51370125/1d9cae84-afbc-4399-8835-648e24f367c8)

2023-06-30 08:32 UTC, liliu-z requested changes

2023-06-30 08:32 UTC, liliu-z commented on vectordb_bench/backend/cases.py
> +
Can we binding timeout with specific case? Since different dataset, dim can also affect the performance

2023-07-04 05:58 UTC, liliu-z commented
/lgtm
/approve

2023-07-04 05:58 UTC, liliu-z approved these changes

2023-07-04 06:37 UTC, alwayslove2013 commented on vectordb_bench/models.py
> +        max_qps = 10 if max_qps < 10 else max_load_dur
if qps < 10 then qps = load_dur ...
spelling error?

2023-07-04 07:04 UTC, alwayslove2013 approved these changes

2023-07-04 07:04 UTC, merged