Redis client
zilliztech/VectorDBBench pull request #198
Opened 2023-07-14 16:42 UTC by s-gruneberg

Draft of a redis client. I have been running it locally using docker.

2023-07-17 02:31 UTC, liliu-z commented
Hi @s-gruneberg Thanks for contribution!! BTW, can I ask is this for Redis Cloud or Redis opensource?

2023-07-17 07:39 UTC, XuanYang-cn commented
/assign

2023-07-17 16:35 UTC, s-gruneberg commented
@liliu-z this is for redis open source, it is similar to the pgVector implementation where it takes a connection string. To my knowledge it should work with redis cloud if the connection to the cloud database is set up. It might take some slight tweaking.

2023-07-18 01:24 UTC, s-gruneberg commented
I realized that my filter search is not working properly, closing this PR until I fix it.

2023-07-18 21:21 UTC, s-gruneberg commented
> @s-gruneberg any update on this?

Yes, all unit tests are passing and filter search is working. As far as I can tell it's good to go. 
Let me know if you have any questions or need me to modify anything / fix errors!

2023-07-19 09:05 UTC, liliu-z commented
Sure, let test this a little bit and get back to you! Plz know that this may take some time due to the lack of human power.

2023-07-24 03:47 UTC, XuanYang-cn requested changes

2023-07-24 03:47 UTC, XuanYang-cn commented on vectordb_bench/backend/clients/redis/config.py
> +    host: str = ""
Please refer to https://github.com/zilliztech/VectorDBBench/blob/675b48f0d2b5561886af17dd897d789bd5e76f5b/vectordb_bench/backend/clients/qdrant_cloud/config.py#L8

SecretStr is a type not a value. Please change host to SecretStr type too. These are both sensitive info.

2023-07-24 03:47 UTC, XuanYang-cn commented on vectordb_bench/backend/clients/redis/config.py
> +    name: str = ""
Same as Chorma, I don't see any usage of param name, please remove it if it's not essentail for connection with the server.

2023-07-24 03:48 UTC, XuanYang-cn commented
It would be better if you could squish all of these changes together into one single commit. This will make it easier to track changes and maintain a more organized version history

2023-07-26 08:15 UTC, XuanYang-cn commented
LGTM

@s-gruneberg Seems this PR has some conflicts with the chroma client one, could you resolve the conflicts?

2023-07-27 02:42 UTC, XuanYang-cn approved these changes

2023-07-27 02:43 UTC, XuanYang-cn commented
@s-gruneberg Please squish the two commits together into one single commit. It cannot be auto rebased so unable to merge.

2023-07-28 05:09 UTC, s-gruneberg commented
@XuanYang-cn 
I'm having some trouble squashing it: 
Github is flagging my squashed commit as having a merge conflict when as far as I can tell there is no conflict. Resolving conflict (on github) gives me an additional commit titled "Merge branch main..." with no differences from previous commit. 

I'm not sure how to fix this on my end because i'm going in circles. If I "resolve" merges on github it makes two commits. If I squash those commits to one (current state) github says there are merge conflicts.

Is it possible to squash on PR merge? If so I can 'resolve' the conflicts and end up with two commits again.

2023-07-28 19:13 UTC, s-gruneberg commented
@XuanYang-cn 
Figured it out! Thanks for your patience!

2023-08-01 03:38 UTC, merged